### ISSUE TITLE
Using application-only authentication Twitter

### ISSUE THREAD

**Issue by rpwagner** [sdsc/sandbox-tweeteor#2]
@23ss23 & @ThomasJGarcia can you look at Twitter's authentication for applications [1]? This looks more appropriate than using an individual's tokens. If you think it will work I'll sign up for one and we'll work out how to manage the credential.

[1] https://dev.twitter.com/oauth/application-only

**Comment by tomgarcia** [comment]
Tweeteor already uses an application only token.  Currently it's using a
token belonging to my account.

**Comment by rpwagner** [comment]
Thanks. I'll sign up for one and make it available for the instance at SDSC. As we consider other feeds I'll be interested in how similar the authentication choices are.
